spring:
  application:
    name : zuul-edge-server
  profiles:
    active: localhost


info:
  component: Zuul Edge Server

server:
  port: 8762

zuul:
  routes:
    product-service:
      path: /api/product/**
      service-id: product-service
      strip-prefix: false
---

spring:
  profiles: localhost

eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka
  instance:
    instance-id: ${spring.application.name}:${random.uuid}

---
spring:
  profiles: stage

eureka:
  client:
    service-url:
      default-zone: http://eureka-server:8761/eureka
  instance:
    instance-id: ${spring.application.name}:${random.uuid}

